// ACTION TYPES;

//All ACUNITs
export const FETCH_ALL_ACUNITS = "FETCH_ALL_ACUNITS";

export const ADD_ACUNIT = "ADD_ACUNIT";
export const DELETE_ACUNIT = "DELETE_ACUNIT";
export const EDIT_ACUNIT = "EDIT_ACUNIT";

//Single ACUNIT
export const FETCH_ACUNIT = "FETCH_ACUNIT";

//All HISTORY
export const FETCH_ALL_HISTORY = "FETCH_ALL_HISTORY";
export const ADD_HISTORY = "ADD_HISTORY";
export const DELETE_HISTORY = "DELETE_HISTORY";
export const EDIT_HISTORY = "EDIT_HISTORY";

//Single HISTORY
export const FETCH_HISTORY = "FETCH_HISTORY";

//all Status
export const FETCH_ALL_STATUS = "FETCH_ALL_STATUS"
//single status
export const FETCH_STATUS = "FETCH_STATUS"
//all VENDOR
export const FETCH_ALL_VENDOR = "FETCH_ALL_VENDOR"
//Single VENDOR
export const FETCH_VENDOR = "FETCH_VENDOR"


//all MANAGEMENT
export const FETCH_ALL_MANAGEMENT = "FETCH_ALL_MANAGEMENT"
//Single MANAGEMENT
export const FETCH_MANAGEMENT = "FETCH_MANAGEMENT"