// ACTION TYPES;

//All ACUNITs
export const FETCH_ALL_ACUNITS = "FETCH_ALL_ACUNITS";

export const ADD_ACUNIT = "ADD_ACUNIT";
export const DELETE_ACUNIT = "DELETE_ACUNIT";
export const EDIT_ACUNIT = "EDIT_ACUNIT";

//Single ACUNIT
export const FETCH_ACUNIT = "FETCH_ACUNIT";

//All HISTORY
export const FETCH_ALL_HISTORY = "FETCH_ALL_HISTORY";
export const ADD_HISTORY = "ADD_HISTORY";
export const DELETE_HISTORY = "DELETE_HISTORY";
export const EDIT_HISTORY = "EDIT_HISTORY";

//Single HISTORY
export const FETCH_HISTORY = "FETCH_HISTORY";
